# Generated by Django 4.0.2 on 2022-02-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('AnimalId', models.AutoField(primary_key=True, serialize=False)),
                ('AnimalName', models.CharField(max_length=500)),
                ('Shelter', models.CharField(max_length=500)),
                ('DateOfArriving', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('ShelterId', models.AutoField(primary_key=True, serialize=False)),
                ('ShelterName', models.CharField(max_length=500)),
            ],
        ),
    ]
